- platform: ping
  hosts:
    ping_aleksander_iphone: 192.168.20.20
    ping_astrid_iphone: 192.168.20.21

- platform: iphonedetect
  consider_home: 100
  scan_interval: 12
  new_device_defaults:
    track_new_devices: true
  hosts:
    aleksander_iphone_wifi: 192.168.20.20
    astrid_iphone_wifi: 192.168.20.21